# ANÁLISIS DESCRIPTIVO

En este notebook se realizará el análisis descriptivo de cada variable presente en el conjunto de datos `temporada1.parquet`.

El objetivo de esta etapa es conocer la estructura y las características generales de los datos, identificar posibles valores faltantes o inconsistencias y obtener una primera aproximación a la distribución de las variables de interés.

In [2]:
# Cargamos los paquetes necesarios
import matplotlib.pyplot as plt 
import polars as pl
import seaborn as sns

import pyprojroot

from plotnine import aes, facet_grid, geom_boxplot, geom_line, geom_point, ggplot

In [3]:
# Definir la ruta raiz del proyecto
ROOT = pyprojroot.here()

# Cargamos los datos
datos_entrenamiento = pl.read_parquet(ROOT / "datos" / "temporada1.parquet")

Completada la carga de los datos, se visualizarán las primeras 10 filas del conjunto de datos. Posteriormente, se procederá a explorar sus características generales.

In [4]:
datos_entrenamiento.head(10)

shape: (10, 16)
┌──────────┬───────────────┬────────┬─────────┬───┬─────────┬─────────┬────────┬────────┐
│ pitch_id ┆ release_speed ┆ batter ┆ pitcher ┆ … ┆ plate_x ┆ plate_z ┆ sz_top ┆ sz_bot │
│ ---      ┆ ---           ┆ ---    ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i64      ┆ f64           ┆ i64    ┆ i64     ┆   ┆ f64     ┆ f64     ┆ f64    ┆ f64    │
╞══════════╪═══════════════╪════════╪═════════╪═══╪═════════╪═════════╪════════╪════════╡
│ 2697762  ┆ 93.800003     ┆ 5782   ┆ 5738    ┆ … ┆ -1.23   ┆ 4.1     ┆ 3.7    ┆ 1.82   │
│ 2697773  ┆ 95.599998     ┆ 5782   ┆ 5738    ┆ … ┆ -0.45   ┆ 3.1     ┆ 3.41   ┆ 1.56   │
│ 2697902  ┆ 94.800003     ┆ 5782   ┆ 5842    ┆ … ┆ 0.31    ┆ 2.4     ┆ 3.41   ┆ 1.56   │
│ 2697993  ┆ 87.300003     ┆ 5782   ┆ 5041    ┆ … ┆ 1.11    ┆ 2.21    ┆ 3.7    ┆ 1.73   │
│ 2697995  ┆ 98.599998     ┆ 5782   ┆ 5041    ┆ … ┆ -0.35   ┆ 3.39    ┆ 3.7    ┆ 1.7    │
│ 2697997  ┆ 98.900002     ┆ 5782   ┆ 5041    ┆ … ┆ -0.75   ┆ 2.76    ┆ 3.41   ┆ 1.56   │
│ 2697712  ┆ 95.400002     ┆ 5782   ┆ 5738    ┆ … ┆ -0.16   ┆ 2.36    ┆ 3.41   ┆ 1.56   │
│ 2697720  ┆ 87.400002     ┆ 5782   ┆ 5738    ┆ … ┆ -0.25   ┆ 3.97    ┆ 3.61   ┆ 1.79   │
│ 2697768  ┆ 87.199997     ┆ 5782   ┆ 5738    ┆ … ┆ -0.54   ┆ 3.09    ┆ 3.64   ┆ 1.7    │
│ 2697772  ┆ 86.300003     ┆ 5782   ┆ 5738    ┆ … ┆ 0.61    ┆ -0.19   ┆ 3.67   ┆ 1.64   │
└──────────┴───────────────┴────────┴─────────┴───┴─────────┴─────────┴────────┴────────┘

### Análisis Univariado

A continuación, se presenta el análisis univariado de las variables presentes en la base de datos, describiendo individualmente sus principales características.

En primer lugar, se analizan las variables cuantitativas de la base de datos. Para ello, se calculan medidas descriptivas de tendencia central, dispersión y posición, tales como la media, mediana, desvío estándar, cuartiles y valores extremos. Estas medidas permiten resumir las principales características de cada variable y comprender su comportamiento general.

In [11]:
# Se seleccionan las variables cuantitativas del Data Set
variables_cuantitativas = datos_entrenamiento.select([
    "release_speed",
    "balls",
    "strikes",
    "pfx_x",
    "pfx_z",
    "plate_x",
    "plate_z",
    "sz_top",
    "sz_bot"
])

# Se arma una tabla resumen, la cual presenta las medidas descriptivas para cada variable cuantitativa
tabla_resumen = variables_cuantitativas.describe()

# Se renombran las medidas descriptivas
tabla_resumen = tabla_resumen.with_columns(
    pl.col("statistic").replace({
        "count": "Cantidad",
        "null_count": "Nulos",
        "mean": "Media",
        "std": "Desvío",
        "min": "Mínimo",
        "25%": "Q1",
        "50%": "Mediana",
        "75%": "Q3",
        "max": "Máximo"
    })
)

tabla_resumen = tabla_resumen.rename({
    "statistic": "Medida"
})

# Se muestra la tabla resumen
tabla_resumen

shape: (9, 10)
┌──────────┬───────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Medida   ┆ release_speed ┆ balls    ┆ strikes  ┆ … ┆ plate_x  ┆ plate_z  ┆ sz_top   ┆ sz_bot   │
│ ---      ┆ ---           ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ f64           ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪═══════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ Cantidad ┆ 709485.0      ┆ 709852.0 ┆ 709852.0 ┆ … ┆ 709485.0 ┆ 709452.0 ┆ 709485.0 ┆ 709440.0 │
│ Nulos    ┆ 367.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 367.0    ┆ 400.0    ┆ 367.0    ┆ 412.0    │
│ Media    ┆ 88.848689     ┆ 0.883648 ┆ 0.895387 ┆ … ┆ 0.043603 ┆ 2.275044 ┆ 3.391976 ┆ 1.57385  │
│ Desvío   ┆ 6.050308      ┆ 0.968486 ┆ 0.828389 ┆ … ┆ 0.846102 ┆ 0.984652 ┆ 0.164649 ┆ 0.089665 │
│ Mínimo   ┆ 30.1          ┆ 0.0      ┆ 0.0      ┆ … ┆ -6.1     ┆ -5.07    ┆ 2.5      ┆ 0.77     │
│ Q1       ┆ 84.599998     ┆ 0.0      ┆ 0.0      ┆ … ┆ -0.53    ┆ 1.64     ┆ 3.3      ┆ 1.51     │
│ Mediana  ┆ 89.900002     ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.04     ┆ 2.28     ┆ 3.41     ┆ 1.56     │
│ Q3       ┆ 93.699997     ┆ 2.0      ┆ 2.0      ┆ … ┆ 0.61     ┆ 2.92     ┆ 3.49     ┆ 1.62     │
│ Máximo   ┆ 103.400002    ┆ 4.0      ┆ 2.0      ┆ … ┆ 9.11     ┆ 9.39     ┆ 4.47     ┆ 2.26     │
└──────────┴───────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

Para las variables cualitativas se examinó la distribución de frecuencias de cada categoría mediante tablas y representaciones gráficas. Esto permite obtener una visión general de la composición de la muestra y de la frecuencia relativa de cada nivel observado.